/* RTC:HokuyoAist
 *
 * Copyright (C) 2009-2010
 *     Geoffrey Biggs
 *     RT-Synthesis Research Group
 *     Intelligent Systems Research Institute,
 *     National Institute of Advanced Industrial Science and Technology (AIST),
 *     Japan
 *     All rights reserved.
 * Licensed under the Eclipse Public License -v 1.0 (EPL)
 * http://www.opensource.org/licenses/eclipse-1.0.txt
 *
 * Component service ports IDL.
 */


#ifndef RANGER_IDL__
#define RANGER_IDL__

#include "ExtendedDataTypes.idl"
#include "InterfaceDataTypes.idl"

module RTC
{

interface Ranger
{
    /// Get the geometry of the device.
    RTC::RangerGeometry GetGeometry();

    /// Set the geometry of the device.
    void SetGeometry(in RTC::RangerGeometry geom);

    /// Turn the ranger device's power on or off.
    void Power(in boolean enable);

    /// Turn on or off the detection and transmission of intensity data.
    void EnableIntensities(in boolean enable);

    /// Get the ranger's current configuration.
    RTC::RangerConfig GetConfig();

    /// Set the ranger's configuration.
    void SetConfig(in RTC::RangerConfig newConfig);
};

}; // module RTC

#endif // RANGER_IDL__

